services:

  kafka:
    image: apache/kafka:4.1.1
    container_name: smart-ebike-kafka

    ports:
      - "9092:9092"

    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_LISTENERS: >
        EXTERNAL://0.0.0.0:9092,
        INTERNAL://0.0.0.0:29092,
        CONTROLLER://0.0.0.0:9093

      KAFKA_ADVERTISED_LISTENERS: >
        EXTERNAL://localhost:9092,
        INTERNAL://kafka:29092

      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: >
        CONTROLLER:PLAINTEXT,
        EXTERNAL:PLAINTEXT,
        INTERNAL:PLAINTEXT

      KAFKA_CONTROLLER_QUORUM_VOTERS: >
        1@localhost:9093

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

    volumes:
      - kafka_data:/tmp/kafka-logs

    healthcheck:
      test:
        [
          "CMD",
          "/opt/kafka/bin/kafka-topics.sh",
          "--bootstrap-server",
          "localhost:9092",
          "--list"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s


  api:
    build:
      context: .
      dockerfile: Dockerfile

    image: ebike-sentinel-api:v4.2
    container_name: ebike-sentinel-api

    ports:
      - "8002:8000"

    env_file:
      - .env

    environment:
      POSTGRES_HOST: host.docker.internal
      POSTGRES_PORT: 5432
      POSTGRES_DB: ebike_db
      POSTGRES_USER: postgres

    extra_hosts:
      - "host.docker.internal:host-gateway"

    restart: unless-stopped



  consumer:
    build:
      context: .
      dockerfile: Dockerfile

    image: ebike-sentinel-api:v4.2
    container_name: ebike-sentinel-consumer

    command:
      - python
      - -m
      - consumer.telemetry_consumer_V42

    env_file:
      - .env

    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      KAFKA_TOPIC: bike_telemetry
      POSTGRES_HOST: host.docker.internal
      POSTGRES_PORT: 5432
      POSTGRES_DB: ebike_db
      POSTGRES_USER: postgres

    extra_hosts:
      - "host.docker.internal:host-gateway"

    depends_on:
      kafka:
        condition: service_healthy

    restart: unless-stopped

volumes:
  kafka_data:




